2019-02-14 15:42:17.090 ERROR scannerclient - <module>: 'XXXX'
Traceback (most recent call last):
  File "/SCANNER/scannerclient.py", line 38, in <module>
    uploadurl = globals()[a]
KeyError: 'XXXX'
2019-02-14 15:42:16.736 ERROR scannerclient - <module>: 'XXXX'
Traceback (most recent call last):
  File "/SCANNER/scannerclient.py", line 38, in <module>
    uploadurl = globals()[a]
KeyError: 'XXXX'
2019-02-14 15:42:16.164 ERROR scannerclient - <module>: 'XXXX'
Traceback (most recent call last):
  File "/SCANNER/scannerclient.py", line 38, in <module>
    uploadurl = globals()[a]
KeyError: 'XXXX'
2019-02-14 15:42:17.076 ERROR scannerclient - <module>: 'XXXX'
Traceback (most recent call last):
  File "/SCANNER/scannerclient.py", line 38, in <module>
    uploadurl = globals()[a]
KeyError: 'XXXX'
2019-02-14 15:42:17.305 ERROR scannerclient - <module>: 'XXXX'
Traceback (most recent call last):
  File "/SCANNER/scannerclient.py", line 38, in <module>
    uploadurl = globals()[a]
KeyError: 'XXXX'
2019-02-14 15:42:17.126 ERROR scannerclient - <module>: 'XXXX'
Traceback (most recent call last):
  File "/SCANNER/scannerclient.py", line 38, in <module>
    uploadurl = globals()[a]
KeyError: 'XXXX'
2019-02-14 15:42:16.948 ERROR scannerclient - <module>: 'XXXX'
Traceback (most recent call last):
  File "/SCANNER/scannerclient.py", line 38, in <module>
    uploadurl = globals()[a]
KeyError: 'XXXX'
2019-02-14 15:42:17.187 ERROR scannerclient - <module>: 'XXXX'
Traceback (most recent call last):
  File "/SCANNER/scannerclient.py", line 38, in <module>
    uploadurl = globals()[a]
KeyError: 'XXXX'
2019-02-14 15:42:16.906 ERROR scannerclient - <module>: 'XXXX'
Traceback (most recent call last):
  File "/SCANNER/scannerclient.py", line 38, in <module>
    uploadurl = globals()[a]
KeyError: 'XXXX'
